[package]
name = "dbc-codegen"
version = "0.1.0"
authors = ["Pascal Hertleif <pascal@technocreatives.com>"]
edition = "2018"
description = "CAN DBC code-gen for embedded Rust"
license = "MIT OR Apache-2.0"
readme = "README.md"

[dependencies]
anyhow = "1.0.33"
can-dbc = "3.0.2"
heck = "0.3.1"
structopt = "0.3.20"

[workspace]
members = [
    ".",
    "testing/rust-integration",
    "testing/can-messages",
    "testing/cantools-messages",
    "testing/can-messages-bitvec",
]

[features]
default = ["bitsh-backend"]
# Use bitsh crate for encoding and decoding of messages
bitsh-backend = []
# Use bitvec crate for encoding and decoding of messages
bitvec-backend = []