[package]
name = "can-messages"
version = "0.1.0"
authors = ["Pascal Hertleif <pascal@technocreatives.com>"]
edition = "2018"

[dependencies]
arbitrary = { version = "1.0", optional = true }
bitsh = { git = "https://github.com/bitbleep/bitsh/" }
bitvec = { version = "0.21", default-features = false }

[features]
default = ["debug", "arb"]
arb = ["arbitrary"]
debug = []
range_checked = []